Test: Generate error when we can't auto-link python2
If there was no `.python` in the project dir, we would try to create it by
symlinking it to `$(type -P python2)`. But if `python2` was not available
in the path, this would quietly create a link of `.python` to itself,
which would then produce confusion and "symlink too deep" errors.

Now, if there's no `.python` we're much clearer about what we're doing
(with a message to the developer) and we fail with an error if we can't
find `python2`.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -15,7 +15,13 @@ cd "$basedir"
 $clean && rm -rf .build
 #   We default to python2 for testing since this should run anywhere.
 #   You may add your own .python link to the interpreter of your choice.
-[[ -L .python ]] || ln -s $(type -P python2) .python
+[[ -L .python ]] || {
+    echo "No .python link found: setting test interpreter to python2."
+    py=$(type -P python2) || {
+        echo 1>&2 "ERROR: Failed to find python2"; exit 1; }
+    echo ".python → $py"
+    ln -s "$py" .python
+}
 source pactivate -q
 
 echo ===== Unit Tests
